// English strings, shared by every screen. One block per role; add yours in a block of your
// own so two roles never edit the same lines. Plurals are functions of the count.

const plural = (count: number, one: string, other: string): string =>
  `${String(count)} ${count === 1 ? one : other}`;

// Block: screens (people, documents, library, settings, account, access, sign in, inbox).
// Every string below is lite's, taken from boasis-lite src/i18n/en.js, except where the spec
// names a field lite does not have.
export const screens = {
  common: {
    close: 'Close',
    save: 'Save',
    saving: 'Saving...',
    loading: 'Loading',
    edit: 'Edit',
    noDate: 'No date yet',
    dueSoon: 'Due soon',
    days: (count: number) => plural(count, 'day', 'days'),
  },
  people: {
    title: 'People',
    subtitle: (count: number) => `${String(count)} sponsored by this company`,
    add: 'Add a person',
    none: 'Nobody yet',
    noneBody:
      'Add the people whose visa this company sponsors. Their renewal dates join the calendar. The passport is not a date of its own, but it is checked against each renewal: immigration will not issue a visa on a passport with less than six months left.',
    missingPassports: (count: number) => `· ${String(count)} without a passport date`,
    missingInsurance: (count: number) => `· ${String(count)} without an insurance date`,
    holder: 'Name',
    holderPlaceholder: 'Maria Santos',
    job: 'Job title',
    jobPlaceholder: 'Sales executive',
    nationality: 'Nationality',
    nationalityPlaceholder: 'Philippines',
    emiratesId: 'Emirates ID',
    emiratesIdPlaceholder: '784-XXXX-XXXXXXX-X',
    // Spec 6.1: the passport number is part of the identity; lite had no field for it.
    passportNumber: 'Passport number',
    expires: 'Visa expires',
    passportExpires: 'Passport expires',
    passportNote: 'Only raised if it leaves less than six months at the time of the renewal',
    insuranceExpires: 'Health insurance ends',
    insuranceNote:
      'The date only. The certificate itself is never uploaded: health data may not leave the UAE',
    expiresIn: (days: string) => `in ${days}`,
    passportFirst: 'Passport first',
    passportMissing: 'No passport date',
    insuranceFirst: 'Insurance first',
    insuranceMissing: 'No insurance date',
    remove: 'This person has left',
    removeSure: (name: string) =>
      `Stop following ${name}? Their dates stop; what is already recorded stays.`,
    leftOn: 'Left on',
    removeConfirm: 'Confirm they left',
    removeKeep: 'Keep them',
    // The person page (lite's visa sheet).
    passportBlocks: (date: string) =>
      `The passport expires ${date}, which leaves less than six months at the time of this renewal. Immigration will not issue the visa on it: the passport has to be renewed first.`,
    passportFine: 'long enough for the next renewal',
    passportMissingWhy:
      'Without it, this person is outside the check: nothing will warn you when their renewal is about to be refused.',
    noPassport: 'Not recorded',
    insuranceBlocksLong: (date: string) =>
      `The cover ends ${date}, before this visa comes up for renewal. Health insurance has been compulsory in every emirate since January 2025 and conditions the permit: the policy has to be renewed first. A broker does it in days.`,
    insuranceFine: 'valid past the next renewal',
    insuranceMissingWhy:
      'Without it, this person is outside the check. The certificate cannot be filed here, so this date has only one way in: the form.',
    noInsurance: 'Not recorded',
    papers: 'Papers on file',
    noPapers:
      'Nothing filed for this person yet. Their visa page and passport belong in Documents.',
    addPaper: 'Add a document',
    about: 'About this person',
    // Spec 6.2, the stage chain, in the row language of the papers block.
    stages: 'Visa stages',
    stageDone: 'Done',
    stageCurrent: 'Now',
    stagePending: 'Ahead',
    stageNotApplicable: 'Does not apply',
    stageBlocked: 'Blocked',
    stageUnknown: 'Unknown',
    stageBy: (date: string) => `by ${date}`,
  },
  documents: {
    title: 'Documents',
    subtitle: (count: number) => `${String(count)} in the vault`,
    add: 'Add a document',
    addNote: 'What it is decides whether it becomes a date you get warned about.',
    chooseFile: 'Choose a file',
    chooseNote: 'A PDF or a photo, up to 25 MB',
    replace: 'Choose another',
    whatIsIt: 'What is this document',
    whose: 'Whose is it',
    choosePerson: 'Choose a person',
    noPeople:
      'No visa is recorded for this company yet. Add the person under People first, then file their document here.',
    expiryOnIt: 'The date printed on it',
    issuedOnIt: 'Issued on',
    becomesADate: 'Nothing else knows this date, so it becomes a deadline of its own.',
    fromThePerson:
      'Taken from what is recorded for this person. Correct it if the paper says otherwise.',
    fileIt: 'File it',
    uploading: 'Uploading...',
    expiresOn: (date: string) => `Expires ${date}`,
    uploadedOn: (date: string) => `Added ${date}`,
    noneTitle: 'Nothing in the vault yet',
    noneBody:
      'Your licences, Ejari and visa pages live here, tied to the company they belong to. Add one, or attach it when you tick a date done.',
    // Spec 5.3, the packs.
    pack: 'Bank KYC pack',
    packTitle: 'Bank KYC pack',
    packNote: 'What is already stored, and what is missing or expired.',
    present: 'On file',
    missing: 'Missing',
    expired: 'Expired',
  },
  library: {
    title: 'Library',
    subtitle: 'What each obligation means, when it falls due, and where the official answer lives',
    search: 'Search the guides',
    clear: 'Clear the search',
    all: 'All',
    mine: 'For you',
    forYou: 'For your companies',
    everythingElse: 'Everything else',
    noMatch: (query: string) => `No guide mentions "${query}".`,
    none: 'No guides yet',
    noneBody:
      'They are being written. Each one will explain an obligation in plain words and point at the authority that decides it.',
    back: 'All guides',
    checked: (date: string) => `Checked ${date}`,
    onThisPage: 'On this page',
    sources: 'Where this comes from',
    disclaimer:
      'A summary to find your way, not legal advice. Every figure was checked against the pages above on the date shown. Where they differ, they win.',
    readNext: 'Read next',
    matchingCard: 'Matching card',
    authority: (name: string) => `The ${name} library`,
    topics: { licence: 'Licence', tax: 'Tax', people: 'People', other: 'Getting started' },
  },
  settings: {
    title: 'Reminders',
    subtitle: 'How we reach you, when we stay quiet, and which of your people hear from us',
    channels: 'Where we send reminders',
    channelsBody:
      'We warn you before a date, never after. Email today; WhatsApp joins it once the business account clears.',
    email: 'Email',
    push: 'Push',
    pushNote: 'On an iPhone, add the app to the home screen first',
    whatsapp: 'WhatsApp',
    whatsappNote: 'Once the business account clears',
    quiet: 'Quiet hours',
    quietNote: 'Nothing is sent between these hours',
    from: 'From',
    to: 'To',
    appearance: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    notices: 'Employee notices',
    noticesBody:
      'When on, a person hears from us only when the action is theirs: a passport renewal, a medical, biometrics, a contract to sign.',
    notifyOn: 'Receives the notices',
    notifyOff: 'Does not receive the notices',
    cannotNotify: 'No email or phone on record',
    noPeople: 'Nobody to notify yet. People appear here once a company sponsors a visa.',
  },
  account: {
    title: 'Account',
    subtitle: 'Your details, how we reach you, and who else can see your companies',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    emailNote: 'Used to sign in',
    mobile: 'Mobile',
    mobileNote: 'How we reach you if something is wrong with your account',
    mobilePlaceholder: '+971 50 000 0000',
    language: 'Language',
    appearance: 'Appearance',
    timeZone: 'Time zone',
    timeZoneNote: (zone: string) => `Every deadline is shown in ${zone}`,
    reachTitle: 'Where we send reminders',
    reachBody:
      'We warn you before a date, never after. Email today; WhatsApp joins it once the business account clears.',
    remindTo: 'Send reminders to',
    remindToNote: 'Leave empty to use the address you sign in with',
    usingAccount: 'Same as your sign-in email',
    badEmail: 'That does not look like an email address.',
    securityTitle: 'Security',
    securityBody:
      'Changing your password sends a link to your inbox. Nothing changes until you use it.',
    password: 'Password',
    sendReset: 'Send me a reset link',
    sending: 'Sending...',
    linkSent: (email: string) => `Link sent to ${email}`,
    signOut: 'Sign out',
    notSet: 'Not set',
    saving: 'Saving',
    saved: 'Saved',
    version: (version: string) => `Boasis · version ${version} · Terms and privacy`,
  },
  access: {
    title: 'Access',
    subtitle: 'Who sees each of your companies, what they may do, and who gets the reminders',
    invite: 'Invite someone new',
    inviteTo: 'Give access to',
    send: 'Send the invitation',
    youTitle: 'You',
    youNote: 'Your own access, and whether you get the reminders',
    youTag: 'You',
    owner: 'Owner',
    person: 'Person',
    actions: 'Actions',
    hasAccount: 'Has an account',
    removePerson: 'Remove from all my companies',
    confirmRemoveOne: (name: string, company: string) =>
      `Remove ${name} from ${company}? They lose access right away. You can give it back later, and they will have to accept again.`,
    confirmRemovePerson: (name: string, companies: string) =>
      `${name} will lose access to ${companies} right away. Continue?`,
    empty: 'Nobody else has access to your companies yet.',
    pickCompany: 'Tick at least one company.',
    give: 'Give access',
    removeHere: 'Remove access',
    onCompanies: (count: number, total: number) => `${String(count)} of ${String(total)} companies`,
    name: 'Name',
    namePlaceholder: 'Layla Haddad',
    email: 'Email',
    emailPlaceholder: 'accountant@firm.ae',
    already: 'That person already has access to this company.',
    // Spec 4.1: the role is named in the owner's words; templates fill the grid.
    roleName: 'Role',
    roleNamePlaceholder: 'PRO, Accountant, Operations manager',
    template: 'Start from',
    custom: 'Blank',
    sameEverywhere: 'Same settings for every company',
    perCompany: (company: string) => `In ${company}`,
    areas: 'What they can reach',
    responsible: 'Responsible',
    responsibleNote: 'Gets the reminders for this area',
    levels: { none: 'Nothing', view: 'View', edit: 'Edit' },
    editAccess: (name: string, company: string) => `${name} in ${company}`,
    templates: {
      manager: 'Manager',
      managerNote: 'Edit everything except access and billing.',
      pro: 'PRO',
      proNote: 'Documents view, people edit, tasks assigned to them.',
      accountant: 'Accountant',
      accountantNote: 'Tax and documents view, plus the small set they answer for.',
    },
    remindersNote:
      'Whoever is responsible for an area gets its reminders. If nobody is, every owner does.',
  },
  gate: {
    brand: 'Boasis',
    brandSub: 'Compliance',
    claimLead: 'You will not',
    claimAccent: 'miss a date',
    said: 'Register your licences once. Every renewal, filing and expiry that follows from them is worked out for you, and you hear about it long before the day.',
    proofs: [
      [
        'Your licences, typed once.',
        'Free zone companies, in any of the 42 UAE free zones. Mainland is coming soon.',
      ],
      [
        'The calendar builds itself.',
        'Renewal, VAT, corporate tax, visas and lease, worked out from your answers and your zone\u2019s rules.',
      ],
      ['We warn you first.', 'By email, from ninety days out and again as the day comes closer.'],
    ],
    legal:
      'Your documents stay yours. They are never shared, and you can take them with you at any time.',
    stepSignin: 'Sign in',
    stepSignup: 'New account',
    stepForgot: 'Reset',
    titleSignin: 'Welcome back',
    titleSignup: 'Start your calendar',
    titleForgot: 'Forgotten password',
    subSignin: 'Everything is where you left it.',
    subSignup: 'Two minutes now, and the dates take care of themselves.',
    subForgot: 'We send a link that works for one hour. Nothing changes until you use it.',
    ctaSignin: 'Sign in',
    ctaSignup: 'Create my account',
    ctaForgot: 'Send the link',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    password: 'Password',
    choosePassword: 'Choose a password',
    again: 'Type it again',
    mismatch: 'The two do not match.',
    firstPlaceholder: 'Layla',
    lastPlaceholder: 'Haddad',
    emailPlaceholder: 'you@company.ae',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    busy: 'One moment',
    sent: (email: string) =>
      `Check ${email}. The link signs you in and takes you straight to a new password.`,
    back: 'Back to sign in',
    forgot: 'I forgot my password',
    noAccount: 'No account yet?',
    createOne: 'Create one',
    haveAccount: 'Already registered?',
    signIn: 'Sign in',
    language: 'English',
  },
  inbox: {
    title: 'Inbox',
    subtitle: 'The reminders due to go out in the next 30 days',
    waiting: (count: number) => plural(count, 'thing waiting', 'things waiting'),
    heading: 'Nothing waiting',
    nothing: 'When a date comes close, or someone invites you, it appears here.',
    fires: (date: string) => `Sent ${date}`,
    scheduled: (date: string) => `Scheduled ${date}`,
    daysBefore: (count: number) => `${plural(count, 'day', 'days')} before`,
    onTheDay: 'on the day',
    overdue: (count: number) => `${plural(count, 'day', 'days')} after`,
    to: (who: string) => `to ${who}`,
    everyOwner: 'every owner',
    by: (channels: string) => `by ${channels}`,
    noChannel: 'no channel on',
  },
} as const;

// Block: screens (home, dial, company page and its sheets). Lite's strings as typed constants;
// a value with {count} is a plural, picked with plural() from lib/format.

export const en = {
  brand: { name: 'Boasis' },

  nav: {
    home: 'Home',
    companies: 'Companies',
    access: 'Access',
    guides: 'Guide',
    compliance: 'Compliance',
    services: 'Services',
    account: 'Your account',
    notifications: 'Notifications',
    notificationsCount: {
      one: 'Notifications, {count} waiting',
      other: 'Notifications, {count} waiting',
    },
  },

  empty: {
    title: 'Register your first licence',
    body: 'Type what is printed on it. From there, every renewal, filing and expiry that follows is worked out for you.',
    cta: 'Add a company',
  },

  urgent: {
    title: 'Urgent',
    count: { one: '{count} thing', other: '{count} things' },
    overdueBy: { one: '{count} day late', other: '{count} days late' },
    passportBlocks: '{name} cannot renew: passport too short',
    insuranceBlocks: '{name} cannot renew: health insurance expires first',
    // The side section beside the dial: three groups, each header a link to its list.
    approaching: 'Approaching due date',
    upcoming: 'Upcoming',
    nothingApproaching: 'Nothing due in the next 15 days.',
    nothingUpcoming: 'Nothing due in the next three months.',
    blocked: 'Blocked',
    // The home stage's one item: its label by why it was chosen, and the way to its card.
    topLabel: 'Upcoming',
    dueSoon: 'Due soon',
    open: 'Open',
  },

  year: {
    upcoming: 'Upcoming dates',
    someLate: { one: '{count} date is overdue.', other: '{count} dates are overdue.' },
    lateLine: {
      one: 'The {what} was due {count} day ago. Everything else can wait.',
      other: 'The {what} was due {count} days ago. Everything else can wait.',
    },
    daysLate: { one: 'day late', other: 'days late' },
    handToday: 'Today',
    familyTax: 'Tax',
    familyVisa: 'Visa',
    familyLicence: 'Licence',
    familyOther: 'Other',
    daysLeft: { one: 'day left', other: 'days left' },
    nothingDue: 'nothing due',
    companiesIn: { one: '{count} company · {places}', other: '{count} companies · {places}' },
    allGood: 'Everything is in good standing.',
    companyGood: '{company} is in good standing.',
    nothingOverdueAll: 'Nothing is overdue anywhere. Next up is the {what} for {company}.',
    nothingOverdue: 'Nothing is overdue. Next up is the {what}.',
    statCompanies: { one: 'company', other: 'companies' },
    statToAddLong: 'documents to add',
    statToAdd: 'to add',
    statDatesLong: 'dates ahead',
    statDates: 'dates',
    statSoonLong: 'within 15 days',
    statSoon: 'in 15 days',
    settledCount: { one: '{count} date already settled', other: '{count} dates already settled' },
    archive: 'Archives',
  },

  company: {
    title: 'Your companies',
    subtitle: '{licences} licences in {kinds} different jurisdictions',
    onTheLicence: 'On the licence',
    editLicence: 'Edit',
    whyTheseDates:
      'Every date on this company is worked out from two of these: the expiry date, and the financial year end. Correcting either one moves the calendar with it.',
    allCompanies: { one: 'All companies', other: 'All {count} companies' },
    tabDates: 'Dates',
    tabOffice: 'Office',
    tabDocs: 'Documents',
    tabVisas: 'Visas',
    tabSettings: 'Renewals',
    noVat: 'Not registered',
    dates: '{count} dates',
    slots: {
      one: '{count} company, {limit} included in your plan',
      other: '{count} companies, {limit} included in your plan',
    },
    slotsFull: 'Each company beyond {limit} is an add-on.',
    documentsCount: { one: '{count} document', other: '{count} documents' },
  },

  deadline: {
    dueSoon: 'Due soon',
    ahead: 'Ahead of you',
    dueSoonLower: 'due soon',
    aheadLower: 'ahead of you',
    whatThisIs: 'What this is',
    close: 'Close',
  },

  answers: {
    title: 'Complete your calendar',
    sub: {
      one: '{count} question left, and a few more dates',
      other: '{count} questions left, and a few more dates',
    },
    nothing: 'Nothing left to ask. Your calendar is as complete as we can make it.',
    later: 'Later',
    save: 'Save answers',
    close: 'Not now',
    yes: 'Yes',
    no: 'No',
    number: 'Your answer',
    list: 'Your answer',
    unblocks: 'Decides the {requirement} card.',
    vatPeriodEnd: 'One VAT period ends on',
    vatPeriodEndHint:
      'The FTA does not use calendar quarters: it assigns one of three cycles when you register.',
  },

  event: {
    title: 'Something changed',
    sub: 'One obligation starts counting from the day something happens, not from a calendar.',
    ubo: 'A shareholder changed',
    uboHint:
      'Someone joined or left, shares moved, or a holding company came in. The register must be updated within 15 days.',
    when: 'It happened on',
    declare: 'Set the deadline',
    done: 'Noted. The date is in your calendar.',
  },

  kind: {
    'free-zone': 'Free zone',
    'free-zoneNote': 'IFZA, DMCC, SHAMS, RAKEZ and the rest',
    mainland: 'Mainland',
    mainlandNote: "Licensed by an emirate's economic department",
  },

  addCompany: {
    title: 'Register a licence',
    editStep: 'Company',
    editTitle: 'Edit this licence',
    sub: 'Copy what is printed on the licence. Two minutes, and your calendar builds itself.',
    whereRegistered: 'Where it is registered',
    colour: 'Company colour',
    authority: 'Authority',
    chooseAuthority: 'Choose an authority',
    emirate: 'Emirate',
    onTheLicence: 'As printed on the licence',
    legalName: 'Legal name',
    legalNameHint: 'The full name, with the legal form',
    legalForm: 'Legal form',
    licenceNumber: 'Licence number',
    dates: 'The dates that matter',
    issuedOn: 'Issued on',
    expiresOn: 'Expires on',
    incorporatedOn: 'Incorporated on',
    yearEnd: 'Financial year end',
    yearEndHint: 'Decides the corporate tax deadline, nine months later',
    vat: 'VAT',
    vatRegistered: 'Registered for VAT',
    vatNote: 'Turn this on if you file VAT returns',
    vatPeriod: 'Filing period',
    quarterly: 'Quarterly',
    monthly: 'Monthly',
    add: 'Add this company',
    save: 'Save changes',
    busy: 'One moment',
  },

  licence: {
    step: 'New company',
    how: 'How would you like to add it?',
    photo: 'Take a photo',
    photoNote: 'Point your camera at the licence',
    file: 'Choose a file',
    fileNote: 'A PDF or a photo you already have',
    manual: 'Type it in',
    manualNote: 'Five fields, about two minutes',
    again: 'Try another file',
    notConfigured: 'Reading licences is not switched on for this project yet. Type it in for now.',
  },

  deleteCompany: {
    action: 'Delete',
    title: 'Delete {company}?',
    sub: 'This is permanent. Nothing below can be recovered.',
    reading: 'Counting what this company holds...',
    whatGoes: 'What disappears',
    upcoming: {
      one: '{count} upcoming date stops. Nobody will be reminded of it.',
      other: '{count} upcoming dates stop. Nobody will be reminded of them.',
    },
    done: {
      one: '{count} completed date and its proof leave the history.',
      other: '{count} completed dates and their proof leave the history.',
    },
    documents: {
      one: '{count} document is deleted from the vault, file included.',
      other: '{count} documents are deleted from the vault, files included.',
    },
    visas: {
      one: '{count} visa is no longer followed, with its passport and insurance checks.',
      other: '{count} visas are no longer followed, with their passport and insurance checks.',
    },
    nothingYet: 'Nothing recorded yet besides the licence.',
    keepRecords:
      'Download what you must keep first. UAE law requires business records to be kept for seven years, and the files cannot be recovered.',
    whatStays: 'What does not change',
    stays:
      'The company itself. Boasis only stops following it: the licence, the tax registration and every obligation remain yours.',
    typeToConfirm: 'Type {company} to confirm',
    confirm: 'Delete permanently',
    deletingCompany: 'Deleting the company...',
    freesSlot:
      'It frees one of the {limit} companies on your plan. People who only had access to this company stop counting as seats.',
  },

  documents: {
    attach: 'Attach the document',
    attachNote: 'The new licence, the receipt, the filing confirmation. Optional.',
    replace: 'Choose another',
    uploading: 'Uploading...',
    reference: 'Or a reference number',
    referenceField: 'Reference number',
    referenceNote: 'The receipt or filing number, and the day it was issued.',
    referenceDate: 'Issued on',
  },

  partners: {
    title: 'Services',
    introBody:
      'Tell us what you need and we will put you in touch ourselves. Nothing is sent to the service: your request reaches us, and we make the introduction.',
    whichCompany: 'Which company',
    whatYouNeed: 'What you need',
    notePlaceholder: 'A few lines is enough. What has to be done, and by when.',
    send: 'Send the request',
  },

  obligation: {
    markDone: 'I have done this',
    marking: 'Saving...',
    doneOn: 'Done on {date}',
    undo: 'Not done after all',
    nextOne: 'The next one is already on your calendar.',
    howWorkedOut: 'How this date is worked out',
    needsEvidence: 'Attach the document, or give the reference number and its date.',
  },

  units: {
    daysLate: { one: '{count} day late', other: '{count} days late' },
    days: { one: '{count} day', other: '{count} days' },
    inDays: { one: 'in {count} day', other: 'in {count} days' },
  },

  // The add-company entry (screen 19): two doors, then the existing-company flow.
  addEntry: {
    title: 'Add a company',
    sub: 'A new licence, or one you already hold.',
    newTitle: 'New company setup',
    newLine: 'Get a new licence.',
    existingTitle: 'Upload an existing company',
    existingLine: 'Already licensed. Bring it in.',
    soonTitle: 'The guided setup is on its way',
    soonBody:
      'This is where a new company will be set up step by step: the activity, the place, the licence, the people. It is being built. Until then, a company you already hold can be brought in from the other door.',
    back: 'Back',
    existingSub: 'Two ways in. Either one ends on the same form.',
    upload: 'Upload the licence',
    uploadNote: 'A PDF or a photo. Confirm what is read from it.',
    type: 'Type it in',
    typeNote: 'Five fields, about two minutes',
    readerTitle: 'Confirm what is on the licence',
    readerSub: 'The file on one side, the fields on the other. Correct anything that is wrong.',
    readerStub:
      'Reading the licence is coming. For now the fields are left blank: copy them from the file beside them.',
    readerFile: 'The file',
    readerNoPreview: 'No preview for this file. Open it beside this window to copy from it.',
    doneTitle: 'Already done?',
    doneSub:
      'An older company has usually done some of this. Tick what is behind you, so it does not open with dates already overdue.',
    doneDay0: 'From the first days of the licence',
    doneNothing: 'Nothing to tick: every first-day item is already behind you.',
    questions: 'A few questions',
    questionsSub: 'What the licence does not say, and what buys the rest of the calendar.',
    finish: 'Open the company',
    skip: 'Later',
    saving: 'Saving',
  },

  // The company file route, until its screen is built.
  companyFile: {
    back: 'Back to the company',
    soonTitle: 'Company file coming soon',
    soonBody: 'Everything about this company in one file. It is being built.',
  },

  // The Services tab (spec 9A, MVP 2), behind the services flag.
  services: {
    title: 'Services',
    sub: 'The work behind a card, done by someone who does it every day.',
    soonTitle: 'Coming soon',
    soonBody:
      'A card will offer the service that closes it: the audit, the renewal, the visa run. You will see the pack of documents, the provider, the price and the timing before you ask.',
  },
} as const;

// Block: screens (profile panel and its screens under /me, offices).
export const me = {
  panel: {
    title: 'Your account',
    profile: 'Profile',
    security: 'Security and passwords',
    access: 'Access',
    notifications: 'Notifications and reminders',
    billing: 'Billing',
    companies: 'Managed companies',
    signOut: 'Sign out',
  },
  profile: {
    title: 'Profile',
    sub: 'Your name, how we reach you, and the language of the app',
    languageNote: 'English for now. Arabic follows.',
  },
  security: {
    title: 'Security and passwords',
    sub: 'Your password, a second step at sign in, and where you are signed in',
    password: 'Password',
    changed: (date: string) => `Changed ${date}`,
    neverChanged: 'Not changed since you joined',
    change: 'Change the password',
    current: 'Current password',
    next: 'New password',
    again: 'Type it again',
    short: 'At least 8 characters.',
    mismatch: 'The two do not match.',
    saved: 'Password changed on this device.',
    save: 'Change it',
    placeholderNote:
      'Kept on this device only. Your sign-in still accepts any password until accounts move to the server.',
    twoStep: 'Two-step verification',
    twoStepNote: 'A code from your phone, asked at every sign in',
    twoStepPlaceholder:
      'A placeholder: the switch is remembered on this device and nothing asks for a code yet.',
    sessions: 'Where you are signed in',
    sessionsNote:
      'A placeholder: only this device is listed, because sessions are not kept on a server yet.',
    thisDevice: 'This device',
    signedIn: (date: string) => `Signed in ${date}`,
    signedInUnknown: 'Signed in before this was recorded',
  },
  billing: {
    title: 'Billing',
    sub: 'Your plan, what you use of it, and the working model behind the price',
    plan: 'Plan',
    standard: 'Standard',
    trial: (days: number) => `Free trial, ${String(days)} days, no card required`,
    used: 'What you use',
    companies: (used: number, included: number) =>
      `${String(used)} of ${String(included)} companies included`,
    members: (used: number, included: number) =>
      `${String(used)} of ${String(included)} member included`,
    peopleLabel: 'People',
    people: (cap: number) => `Up to ${String(cap)} people on visas per company`,
    peopleUsed: (company: string, used: number, cap: number) =>
      `${company}: ${String(used)} of ${String(cap)}`,
    model: 'The working model',
    modelNote:
      'Every figure is an example under discussion, not a price. Nothing is charged today. The unit is the person, not the company.',
    owner: 'Owner',
    ownerNote:
      'Paid by the person who creates the account. Covers your own full access and one more person, set up however you like.',
    member: 'Each further person',
    memberNote:
      'One price for any invited person, whatever their role or how many of your companies they are added to.',
    addOns: 'Add-ons',
    addOnsNote: (block: number) =>
      `One more company, or a block of ${String(block)} more people on one company. Add-ons instead of tiers.`,
    notices: 'Notices',
    noticesNote:
      'Reminders and notices to anyone who does not log in (employees, a landlord, a partner) are unlimited and free.',
    closed: 'Closed companies',
    closedNote: 'Do not count. Their records stay.',
    enterprise: 'Enterprise',
    enterpriseNote: (line: number) =>
      `Above ${String(line)} people in any one company, above a set number of companies, or for custom work.`,
    nonPayment: 'If a payment fails',
    nonPaymentNote: (grace: number, readOnly: number, months: number) =>
      `${String(grace)} days of grace, then read-only for ${String(readOnly)} days with reminders still firing, then reminders stop. Data kept and exportable for ${String(months)} months.`,
    perMonth: (aed: number) => `AED ${String(aed)} a month, example`,
    noPayment: 'No payment is taken here. This page describes the plan; it does not charge.',
  },
  companies: {
    title: 'Managed companies',
    sub: 'The companies you own: their name, the colour of their mark, and their logo',
    edit: 'Edit',
    editTitle: (name: string) => `Edit ${name}`,
    name: 'Name',
    colour: 'Colour of the mark',
    logo: 'Logo',
    chooseLogo: 'Choose a logo',
    logoNote: 'A PNG, JPEG, SVG or WebP up to 512 KB. Kept with the company.',
    replaceLogo: 'Choose another',
    removeLogo: 'Remove the logo',
    tooBig: 'That file is over 512 KB. Choose a smaller one.',
    save: 'Save',
    none: 'No company yet. Add one from the home screen.',
  },
  office: {
    title: 'Office',
    sub: (count: number) =>
      plural(count, 'place of business on this licence', 'places of business on this licence'),
    none: 'No premises yet',
    noneBody:
      'Every licence sits on premises. Add the office, the flexi-desk, the shop or the warehouse, and its lease end, Ejari and rent dates join the calendar.',
    add: 'Add premises',
    edit: 'Edit',
    renew: 'Renew',
    handBack: 'Hand back',
    type: 'Type',
    size: 'Size',
    sqm: (size: number) => `${String(size)} m²`,
    lease: 'Lease',
    leaseLine: (start: string, end: string) => `${start} to ${end}`,
    ejari: 'Ejari',
    ejariLine: (number: string, expiry: string) => `${number}, expires ${expiry}`,
    noEjari: 'Not registered',
    nextRent: 'Next rent instalment',
    rentLine: (date: string, amount: number, method: string) =>
      `${date}, AED ${amount.toLocaleString('en-AE')} by ${method}`,
    noRent: 'None due',
    permits: 'Permits',
    noPermits: 'None recorded',
    quota: 'Visa quota',
    quotaLine: (used: number, allowed: number) => `${String(used)} of ${String(allowed)} used`,
    quotaUnknown: (used: number) => `${String(used)} used, allowance unknown`,
    registered: 'Registered address',
    flexiLine: 'In the zone package. The term follows the licence, no instalments.',
    ended: (date: string) => `Lease ended ${date}`,
    types: {
      'flexi-desk': 'Flexi-desk',
      'shared-desk': 'Shared desk',
      'serviced-office': 'Serviced office',
      'dedicated-office': 'Dedicated office',
      shop: 'Shop',
      warehouse: 'Warehouse',
      land: 'Land',
    },
    approvals: {
      'fit-out-permit': 'Fit-out permit',
      'civil-defence-approval': 'Civil defence approval',
      'municipality-inspection': 'Municipality inspection',
      'signboard-permit': 'Signboard permit',
    },
    methods: { cheque: 'cheque', transfer: 'transfer' },
    // The sheets.
    addTitle: 'Add premises',
    editTitle: 'Edit the premises',
    renewTitle: 'Renew the lease',
    renewSub: 'The new term. The old dates are replaced; the calendar follows.',
    handBackTitle: 'Hand back the premises',
    handBackSub:
      'The lease ends on the day you give back the keys. Clearances need the utility, telecom and access accounts below.',
    handBackOn: 'Handed back on',
    handBackConfirm: 'Hand it back',
    premises: 'The premises',
    address: 'Address',
    sizeSqm: 'Size in square metres',
    isRegistered: 'This is the registered address',
    theLease: 'The lease',
    landlord: 'Landlord or zone',
    start: 'Lease start',
    end: 'Lease end',
    notice: 'Notice period in days',
    rent: 'Rent in AED',
    deposit: 'Security deposit in AED',
    ejariNumber: 'Ejari number',
    ejariExpiry: 'Ejari expiry',
    capacity: 'Capacity',
    quotaAllowed: 'Visa quota allowed',
    quotaUsed: 'Visa quota used',
    services: 'Services',
    electricity: 'Electricity and water account',
    telecom: 'Telecom account',
    access: 'Building access',
    parking: 'Parking',
    save: 'Save',
    saveNew: 'Add these premises',
    busy: 'One moment',
    needEnd: 'The lease end has to be after its start.',
  },
} as const;

// Block: screens (compliance board, card page, decision point, trackers, calendar, cost view).
// The board's words are the spec's (7, 7.1, 10, 14); the rest is lite's sheet language.

export const compliance = {
  board: {
    title: 'Your compliance status',
    subtitle: 'A live snapshot of where you stand. Tap any item for what to do next.',
    company: 'Company',
    allCompanies: 'All companies',
    state: 'State',
    empty: 'Nothing matches this filter.',
    open: 'Open',
    count: (count: number) => plural(count, 'card', 'cards'),
    filters: {
      all: 'All',
      urgent: 'Urgent',
      overdue: 'Overdue',
      expiring: 'Expiring',
      'action-soon': 'Action soon',
      'decision-needed': 'Decision needed',
      unknown: 'Unknown',
      'on-track': 'On track',
      complete: 'Complete',
    },
    blocked: 'Blocked',
    decide: 'Answer the decision point',
    answer: 'Answer',
    saving: 'Saving...',
    yes: 'Yes',
    no: 'No',
    registered: 'Registered',
    notRegistered: 'Not registered',
    vatQuestion: 'Is this company registered for VAT?',
  },
  line: {
    due: (date: string) => `Due ${date}`,
    done: (date: string) => `Done ${date}`,
    pending: 'Still to do, no date of its own',
    unknown: 'A fact is missing',
  },
  unassigned: 'Unassigned',
  unknownWhy: {
    vat: 'The VAT status has not been entered.',
    vatPeriod: 'The VAT period end and its length are not entered yet.',
    kyc: 'The bank has not given a KYC refresh date yet.',
    bank: 'Whether the company has a bank account is not entered.',
    ubo: 'The UBO declaration date is not entered in the company file.',
    unemployment: 'The unemployment insurance certificate has no end date recorded.',
    passport: 'The passport expiry is not recorded.',
    permit: (authority: string) =>
      `The ${authority} file does not give the entry permit validity, so this stage has no clock.`,
    emiratisation: 'Needs the headcount and the sector, which the company file does not carry yet.',
    file: (authority: string) => `The ${authority} file does not carry this fact.`,
  },
  card: {
    back: 'Compliance',
    daysLeft: { one: '{count} day left', other: '{count} days left' },
    daysLate: { one: '{count} day late', other: '{count} days late' },
    noDate: 'No date of its own',
    actBy: (date: string) => `Act by ${date}`,
    actByNote: 'The last working day on or before the date.',
    responsible: 'Responsible',
    steps: 'What to do next',
    stepsUnknown: 'The authority file has no playbook for this requirement yet: unknown.',
    stepsSource: 'Where the steps come from',
    assign: 'Assign',
    nobody: 'Nobody',
    documents: 'Documents needed',
    documentsNone: 'This card closes on a reference, no document is required.',
    onFile: 'On file',
    missing: 'Not on file',
    fee: 'Fee',
    feeUnknown: 'unknown',
    ifMissed: 'If missed, in the library’s words',
    library: 'Read the guide',
    libraryNone: 'No guide for this requirement yet.',
    reference: 'Log a reference',
    referenceNote: 'A receipt or filing number, and the day it was issued. Kept on the card.',
    referenceField: 'Reference number',
    referenceDate: 'Issued on',
    logIt: 'Log it',
    logged: 'References logged',
    close: 'Close this card',
    closeNote:
      'The last step asks for the evidence: the new document, or a reference number and date. Nobody closes a card without one.',
    closed: 'Closed',
    closedNext: 'Closed. The next one is already on your calendar.',
    closedFinal: 'Closed.',
    evidence: 'Evidence',
    document: 'Document',
    tracker: 'Open the tracker',
    person: 'Open the person',
    decision: 'Open the decision point',
    stepDone: 'Done',
    stepToDo: 'To do',
  },
  decision: {
    title: 'Renew, cancel or shrink?',
    kicker: 'Decision point',
    opens: (date: string) => `Opens ${date}`,
    lead: (days: number) => `${String(days)} days before the licence expires`,
    expires: (date: string) => `The licence expires ${date}`,
    notOpen: 'The question opens ninety days before the licence expires. Nothing to answer yet.',
    answered: (answer: string, date: string) =>
      `You answered ${answer} for the licence expiring ${date}.`,
    change: 'Change the answer',
    renew: 'Renew',
    renewLine:
      'The renewal checklist for the authority, starting with the longest prerequisite. Ends with uploading the new licence.',
    cancel: 'Cancel',
    cancelLine: 'The cancellation sequence with each clock: visas first, notices, deregistration.',
    shrink: 'Shrink',
    shrinkLine:
      'Fewer visas, fewer activities or a cheaper package, all before the renewal date so the renewal is charged at the smaller size.',
    bundle: 'What renews together',
    window: 'Cancellation window',
    windowDays: (days: number) => `${String(days)} days`,
    feeInside: 'Cancelling inside the window',
    feeOutside: 'Cancelling outside the window',
    unknown: 'unknown',
    source: {
      document: 'From your agreement',
      'authority-file': 'From the authority file',
      'owner-answer': 'From your answer',
      unknown: 'Not known yet',
    },
    unconfirmed: (title: string) => `Read from ${title}, not confirmed, so not used`,
    ignored: 'If nothing is answered',
    ignoredLine: 'Reminders escalate to every owner. The licence card shows "decision needed".',
    closingTitle: 'Are you thinking of closing?',
    closingLine: 'A full LLC closure runs three to six months, so the portal asks 180 days out.',
    closingSince: (date: string) => `Asked since ${date}`,
    closingYes: 'Yes, thinking of closing',
    closingNo: 'No, carrying on',
    closingAnswered: (yes: boolean) =>
      yes ? 'You said you are thinking of closing.' : 'You said you are carrying on.',
    shrinkVisas: 'Visas you could release',
    shrinkActivities: 'Activities you could drop',
    shrinkPackages: 'Packages the authority offers',
    shrinkNone: 'nothing recorded',
    openTracker: 'Open the tracker',
  },
  tracker: {
    renewal: 'Renewal tracker',
    cancellation: 'Cancellation tracker',
    amendment: 'Amendment tracker',
    kicker: 'Tracker',
    clocks: 'Clocks',
    noClocks: 'No card is running a clock for this tracker yet.',
    steps: 'Steps',
    noSteps: 'The authority file has no steps for this sequence: unknown.',
    notOpen: 'Ticks are kept on the card once one is open for this sequence.',
    unknownClock: 'unknown',
  },
  calendar: {
    title: 'Calendar',
    subtitle: 'Every date, across your companies, in order',
    subtitleOne: 'Every date of this company, in order',
    subscribe: 'Subscribe',
    feedTitle: 'Your calendar feed',
    feedLine:
      'Apple Calendar, Google Calendar and Outlook all accept this link. It carries company data, so it can be regenerated and revoked.',
    feedPlaceholder: 'Placeholder. The real link is issued by the backend.',
    copy: 'Copy the link',
    nothing: 'No dates ahead.',
    settled: (count: number) => plural(count, 'date already settled', 'dates already settled'),
  },
  cost: {
    title: 'Costs',
    subtitle: 'The next twelve months, by month, across your companies. No surprise bills.',
    unknown: 'unknown',
    known: (amount: string) => `AED ${amount}`,
    unknownCount: (count: number) =>
      plural(count, 'line without a known fee', 'lines without a known fee'),
    total: 'Twelve months',
    totalNote: 'Known fees only. Where no fee is known the line says so.',
    empty: 'Nothing due this month.',
    kinds: {
      licence: 'Licence renewal',
      card: 'Card renewal',
      lease: 'Lease instalment',
      leaseEnd: 'Lease renewal',
      visa: 'Visa renewal',
      emiratesId: 'Emirates ID renewal',
      workPermit: 'Work permit renewal',
      insurance: 'Insurance renewal',
      audit: 'Audit',
      tax: 'Tax filing',
    },
    package: (name: string) => name,
  },
} as const;

// Block: onboarding-screens (onboarding v2, the account and steps 1 to 9). Titles, why lines,
// field reasons and messages are the spec's words (Boasis-Onboarding-v2, sections 3 and 5).
// Amounts and day counts that come from content are passed in, never written here.
const days = (count: number) => plural(count, 'day', 'days');

export const onboarding = {
  common: {
    continue: 'Continue',
    later: "I'll add this later",
    notSure: 'Not sure',
    back: 'Back',
    saving: 'Saving...',
    loading: 'Loading',
    required: 'Required',
    optional: 'Optional',
    stepOf: (step: number, count: number) => `Step ${String(step)} of ${String(count)}`,
    yes: 'Yes',
    no: 'No',
    remove: 'Remove',
    add: 'Add',
    unknown: 'unknown',
    source: 'Source',
    lastChecked: (date: string) => `Last checked ${date}`,
    whoCanTell: (who: string) => `Who can tell you: ${who}.`,
    unknownRule: 'We do not have a source for this yet.',
    farFuture: 'Is this right?',
    farFutureConfirm: 'Yes, this date is right',
    expiryBeforeIssue: 'The expiry date must be after the issue date.',
    notAfterToday: 'This date cannot be after today.',
    incompleteDate: 'Choose the day, the month and the year.',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    notSureChosen: 'Marked as not sure. We will ask again.',
    laterChosen: 'Marked to add later.',
    change: 'Change',
    error: 'Something went wrong. Try again.',
  },
  grades: {
    confirmed: 'confirmed',
    reported: 'reported',
    unclear: 'unknown',
    own: 'your date',
  },
  who: {
    you: 'you',
    person: 'the person',
    agent: 'your agent',
    accountant: 'your accountant',
    zone: 'the zone',
    fta: 'the FTA',
  },
  upload: {
    label: (what: string) => what,
    why: 'Kept in your vault',
    choose: 'Upload a file',
    types: 'PDF, JPG or PNG, up to 20 MB',
    wrongType: 'Upload a PDF, JPG or PNG file.',
    tooBig: 'The file is larger than 20 MB.',
    kept: (name: string) => `${name}, kept in your vault`,
  },
  account: {
    step: 'Create your account',
    title: 'Create your account',
    why: 'Your account keeps your company file private to you and the people you invite.',
    fullName: 'Full name',
    fullNameWhy: 'Your name on the account',
    fullNameError: 'Enter your name, 2 to 100 characters.',
    email: 'Email',
    emailWhy: 'Sign-in and all reminders go here',
    emailError: 'Enter a valid email address.',
    password: 'Password',
    passwordWhy: 'Protects your company file. At least 12 characters.',
    passwordShort: 'Use at least 12 characters.',
    passwordBreached: 'This password appears in a known list of leaked passwords. Choose another.',
    passwordUnchecked: 'We could not check this password right now. Try again in a moment.',
    twoStep: 'Two-step sign-in with an authenticator app',
    twoStepWhy: 'Extra protection for your documents. You can turn it on later in settings.',
    plan: 'Plan',
    planWhy: 'Sets how many companies you can add',
    planOption: (companies: number, priceAed: number) =>
      companies === 1
        ? `1 company, AED ${String(priceAed)} a month`
        : `Up to ${String(companies)} companies, AED ${String(priceAed)} a month`,
    terms: 'I accept the terms and privacy notice',
    termsVersion: (version: string) => `Version of ${version}`,
    termsError: 'Tick to accept the terms and privacy notice.',
    create: 'Create account',
    exists: 'An account with this email already exists. Sign in instead.',
  },
  verify: {
    title: 'Check your email',
    body: (email: string) =>
      `We sent a link to ${email}. Open it to verify your email. Onboarding opens once it is verified.`,
    resend: 'Send the link again',
    resent: 'Sent again.',
    demo: 'Verify now',
    demoNote: 'There is no email in this demo: this button stands in for the link.',
    verified: 'Your email is verified.',
    noAccount: 'Create your account first',
    noAccountBody:
      'This sign-in has no account yet. Sign out and create an account to add a company.',
    signOut: 'Sign out and create an account',
  },
  where: {
    title: 'Where is your company licensed?',
    why: 'This decides which rules and steps apply to you.',
    jurisdiction: 'Jurisdiction',
    jurisdictionWhy: 'Rules differ by authority',
    freeZone: 'Free zone',
    mainland: 'Mainland',
    zone: 'Free zone',
    zoneWhy: 'Loads the zone’s rules',
    zoneSearch: 'Search the zones',
    zoneNone: 'No zone matches this search.',
    zoneError: 'Choose the free zone that issued the licence.',
    role: 'Your role in this company',
    roleWhy: 'Who you are to this company',
    roles: {
      owner: 'Owner',
      manager: 'Manager',
      adviser: 'Adviser (accountant, PRO, agent)',
    },
    roleError: 'Choose your role in this company.',
    adviser: 'You can add the company now. Its owner can be invited later.',
    planFullOne: (companies: number, priceAed: number) =>
      `Your plan covers 1 company. Upgrade to up to ${String(companies)} companies for AED ${String(priceAed)} a month.`,
    planFull: (covers: number) => `Your plan covers ${String(covers)} companies.`,
    upgrade: 'Upgrade',
    upgraded: (companies: number) => `Your plan now covers up to ${String(companies)} companies.`,
  },
  mainland: {
    title: 'Mainland is coming soon',
    why: 'We will email you when it opens.',
    emirate: 'Emirate',
    emirateError: 'Choose the emirate.',
    consent: 'Email me when mainland opens',
    consentError: 'Tick to let us email you.',
    join: 'Join the waitlist',
    joined: 'You are on the list. We will email you when mainland opens.',
    instead: 'Add a free zone company instead',
  },
  licence: {
    title: 'Your licence',
    companyName: 'Company name (as on licence)',
    companyNameWhy: 'Your company file',
    companyNameError: 'Enter the company name as printed on the licence.',
    licenceNumber: 'Licence number',
    licenceNumberWhy: 'Your company file; stops duplicates',
    licenceNumberError: 'Enter the licence number.',
    needsIdentity: 'Add the company name and licence number to create the company file.',
    legalForm: 'Legal form',
    legalFormWhy: 'Some requirements depend on it',
    legalForms: {
      fze: 'FZE',
      fzco: 'FZCO',
      'free-zone-llc': 'FZ-LLC',
      branch: 'Branch',
      other: 'Other',
    },
    status: 'Licence status',
    statusWhy: 'So we start from where you really are',
    statuses: {
      active: 'Active',
      expired: 'Expired',
      'renewal-in-progress': 'Renewal in progress',
      'being-cancelled': 'Being cancelled',
    },
    statusError: 'Choose the licence status.',
    issueDate: 'Licence issue date',
    issueDateWhy: 'Renewal dates',
    expiryDate: 'Licence expiry date',
    expiryDateWhy: 'Renewal dates and reminders',
    expectedNewExpiry: 'Expected new expiry date',
    expectedNewExpiryWhy: 'Reminders restart from the new date once entered.',
    beingCancelled:
      'This company is flagged as being cancelled. The cancellation workflow is offered here once it is built.',
    term: 'Licence term',
    termWhy: 'Some zones issue multi-year licences',
    terms: { 1: '1 year', 2: '2 years', 3: '3 years or more' },
    termYears: 'Number of years',
    incorporation: 'Date of incorporation',
    incorporationWhy:
      'On your Certificate of Incorporation or Registration, not your licence. After a renewal the licence issue date changes; this date never does. Needed for the corporate tax deadline.',
    activities: 'Activities',
    activitiesWhy: 'Some activities need approvals later. One activity per line.',
    website: 'Website',
    websiteWhy: 'Company file',
    handler: 'Who handles your zone paperwork?',
    handlerWhy: 'Every step later says "you do this" or "send this to your agent"',
    handlers: {
      self: 'Me',
      agent: 'An agent or partner',
      zone: 'The zone directly',
    },
    handlerError: 'Choose who handles your zone paperwork.',
    agentName: 'Agent or partner name',
    agentEmail: 'Agent or partner email',
    channel: (zone: string) => `How ${zone} takes applications`,
    licenceFile: 'Licence file',
    certificateFile: 'Certificate of incorporation',
    duplicate: 'This company is already on Boasis. Ask its owner to invite you.',
    zoneFacts: (zone: string) => `${zone}: renewal facts`,
    leaseToRenew: 'Lease must be valid to renew',
    renewsTogether: 'What renews together',
    afterExpiry: 'What happens after expiry',
    factUnknown: 'unknown',
    factWho: 'the zone or your agent',
  },
  expired: {
    title: (count: number) => `Your licence expired ${days(count)} ago.`,
    titleUndated: 'Your licence has expired.',
    zoneSays: (zone: string) => `What ${zone} says happens next`,
    unknown:
      'We do not have this zone’s rules on late renewal yet. Contact the zone or your agent today.',
    start: 'Start renewal now',
    startBody: (zone: string) =>
      `The renewal workflow is being built. Until then, here is ${zone}'s renewal checklist and contact.`,
    checklist: 'Renewal checklist',
    contact: 'Contact',
    noChecklist: 'We do not have this zone’s renewal checklist yet. Ask the zone or your agent.',
  },
  people: {
    title: 'Owners and managers',
    why: 'Their passports, visas and Emirates IDs have dates we will watch for you.',
    fullName: 'Full name',
    fullNameWhy: 'Company file',
    fullNameError: 'Enter the person’s full name.',
    email: 'Email',
    emailWhy: 'To invite them later',
    emailError: 'Enter a valid email address, or leave it empty.',
    role: 'Role in this company',
    roleWhy: 'Who owns and who signs',
    roles: { shareholder: 'Shareholder', manager: 'Manager', both: 'Both' },
    roleError: 'Choose the role in this company.',
    ownership: 'Ownership %',
    ownershipWhy: 'Ownership records (UBO)',
    ownershipError: 'Enter a number from 0 to 100.',
    ownershipTotal: 'The total across shareholders must not pass 100.',
    passport: 'Passport expiry',
    passportWhy: (months: number) =>
      `A passport needs at least ${String(months)} months left to renew a UAE residence visa.`,
    sponsor: 'Residence visa: who sponsors it?',
    sponsorWhy: 'Only visas under this company use its quota',
    sponsors: {
      'this-company': 'This company',
      'my-company': 'Another of my companies',
      family: 'Family',
      'other-employer': 'Another employer',
      'not-resident': 'Not a UAE resident',
    },
    sponsorError: 'Choose who sponsors the residence visa.',
    whichCompany: 'Which of your companies?',
    notOnBoasis: 'It is not on Boasis yet',
    addThatNext: 'Add that company next',
    visa: 'Residence visa expiry',
    visaWhy: 'Visa reminders',
    emiratesId: 'Emirates ID expiry',
    emiratesIdWhy: 'Emirates ID reminders',
    passportFile: 'Passport',
    visaFile: 'Visa',
    emiratesIdFile: 'Emirates ID',
    pick: 'People already on your account',
    pickWhy:
      'Picking someone reuses their passport, visa and Emirates ID. Their role and visa sponsor are asked again.',
    pickAdd: (name: string) => `Add ${name}`,
    addPerson: 'Add another person',
    savePerson: 'Save this person',
    editPerson: 'Edit',
    removePerson: 'Remove from this company',
    none: 'No one added yet.',
    you: 'You',
    reused: 'Their passport, visa and Emirates ID come from their file.',
    rolesLine: (role: string, percent: string | null) =>
      percent === null ? role : `${role}, ${percent}%`,
  },
  office: {
    title: 'Your office',
    why: 'Most zones need a valid office or desk contract to renew your licence.',
    type: 'Office type',
    typeWhy: 'The office decides what the zone asks at renewal',
    types: {
      'flexi-desk': 'Flexi desk or business centre',
      office: 'Office',
      'warehouse-or-land': 'Warehouse or land',
      none: 'None',
    },
    end: 'Contract or lease end date',
    endWhy: 'Lease reminders, timed before the licence',
    renews: 'Renews with the licence?',
    renewsWhy: 'Some zones renew both in one request',
    file: 'Contract file',
    leaseBeforeConfirmed: (zone: string) =>
      `Your lease ends before your licence. ${zone} requires a valid lease to renew your licence.`,
    leaseBeforeOther:
      'Your lease ends before your licence. Check with your zone whether it must be renewed first.',
    businessCentre: (count: number, zone: string) =>
      `Renew your lease if it has under ${String(count)} days left. ${zone} lets you renew it in the same request as your licence.`,
  },
  card: {
    title: 'Visas your company can sponsor',
    why: 'Your establishment card and quota decide whether you can issue or renew visas.',
    expiry: 'Establishment (immigration) card expiry',
    expiryWhy: 'Needed to issue or renew visas',
    allowed: 'Visa quota allowed',
    allowedWhy: 'How many visas the company may sponsor',
    prefilled: (zone: string) =>
      `Prefilled from ${zone}'s quota for a flexi desk. You can change it.`,
    used: 'Visas used now',
    usedWhy: 'Prefilled with the owners and managers this company sponsors. Add your employees.',
    countError: 'Enter a whole number.',
    left: (count: number) => `Visas left: ${String(count)}`,
    over: 'Your records show more visas than your quota allows. Check with your zone.',
    file: 'Card file',
    expiredConfirmed: 'While your establishment card is expired you cannot issue or renew visas.',
    otherZones:
      'Most zones need a valid establishment card for visa services. Check with your zone.',
  },
  tax: {
    title: 'Corporate tax',
    question: 'Is the company registered for corporate tax?',
    questionError: 'Choose Yes, No or Not sure.',
    trn: 'Tax registration number (TRN)',
    trnWhy: 'So it is in one place when your bank, accountant or invoices ask for it.',
    trnError: 'A TRN has 15 digits.',
    firstPeriodEnd: 'End date of the first tax period',
    firstPeriodEndWhy:
      'It is on your registration certificate. A first period can run 6 to 18 months, so your financial year end alone cannot tell us your first return date.',
    yearEnd: 'Financial year end',
    yearEndWhy: 'Every return after the first',
    qfzp: 'Will you claim Qualifying Free Zone Person status?',
    qfzpWhy: 'It decides whether your accounts must be audited.',
    returnDue: (date: string) => `Return and payment due ${date}`,
    firstReturnDue: (date: string) => `First return and payment due ${date}`,
    returnUnknown: 'Add the end date of the first tax period to see your first return date.',
    audit: 'Audited financial statements are required.',
    auditDue: 'Audit due date: unknown until sourced.',
    needIncorporation: 'We need your date of incorporation to tell you your deadline.',
    backToLicence: 'Add it in step 2',
    registerBy: (date: string) => `Register by ${date}.`,
    registerReminders: (list: string) => `Reminders ${list} days before.`,
    howToRegister: 'How to register on EmaraTax',
    late: 'You are late to register for corporate tax.',
    registerNow: 'Guide: register now on EmaraTax',
    waiver:
      'The FTA has offered a waiver for late registration. Check its current status on tax.gov.ae.',
    howToCheck: 'How to check your registration on EmaraTax',
    checkTask: 'Task added: Check corporate tax registration.',
    thenYearEnd: 'Then your financial year end, so the first return date can be shown.',
    calculatedReturn: (date: string, first: boolean) =>
      `${first ? 'First return' : 'Return'} and payment due ${date}, calculated from the confirmed rule.`,
    confirmedOnRegister: 'The FTA confirms your first tax period when you register.',
    whichFirstPeriod: 'Which is the end of your first tax period?',
    whichFirstPeriodWhy:
      'Your first financial year can end on either date. It is on your registration certificate once you register.',
    firstPeriodUnknown:
      'We cannot tell your first tax period end from these dates. Task added: ask your accountant.',
  },
  vat: {
    title: 'VAT',
    question: 'Is the company registered for VAT?',
    trn: 'VAT number (TRN)',
    trnWhy: 'So it is in one place when your bank, accountant or invoices ask for it.',
    period: 'Filing period',
    periodWhy: 'Return dates',
    periods: { quarterly: 'Quarterly', monthly: 'Monthly' },
    periodEnd: 'End date of your current or last tax period',
    periodEndWhy: 'It is on your VAT certificate. The FTA sets which months your quarters end.',
    returnDue: (date: string) => `Return and payment due ${date}`,
    returnReminders: (list: string) => `Reminders ${list} days before.`,
    band: 'Taxable sales and imports in the last 12 months',
    bandWhy: 'The FTA looks at your taxable sales and imports over the last 12 months.',
    bands: (voluntary: string, mandatory: string) => ({
      'below-187500': `Below AED ${voluntary}`,
      '187500-375000': `Between AED ${voluntary} and ${mandatory}`,
      'above-375000': `Above AED ${mandatory}`,
    }),
    next30: (mandatory: string, daysAhead: number) =>
      `Do you expect them to pass AED ${mandatory} in the next ${String(daysAhead)} days?`,
    next30Why: (mandatory: string, daysAhead: number) =>
      `You must also register if you expect to pass AED ${mandatory} in the next ${String(daysAhead)} days.`,
    mandatory: 'You must register for VAT.',
    window: 'How long you have to apply is unverified at article level.',
    voluntary: 'You can choose to register.',
    noDeadline: 'No deadline.',
    notRequired: 'Not required now.',
    monthly: (voluntary: string, mandatory: string) =>
      `We will email you on the first of each month: "Have your sales in the last 12 months passed AED ${voluntary} or ${mandatory}?"`,
    askAccountant: 'Task added: Ask your accountant about VAT.',
    howToCheck: 'How to check on EmaraTax',
    checkTask: 'Task added: Check VAT registration.',
    guide: 'Guide: VAT registration',
  },
  year: {
    title: 'Your year',
    why: 'Every date we will watch for you, with where it comes from.',
    next: 'Next 3 things due',
    nextNone: 'Nothing dated yet. Add dates and they appear here.',
    all: 'Your year',
    late: 'Late',
    now: 'Now',
    calculated: 'calculated from the confirmed rule',
    stillNeed: 'We still need',
    stillNeedNone: 'Nothing. Every item is answered.',
    whoCanAnswer: (who: string) => `Who can answer: ${who}`,
    reasons: { unknown: 'You said not sure.', skipped: 'You chose to add this later.' },
    ownDocuments: 'Your own documents',
    ownNone: 'No passport, visa or Emirates ID dates for you yet.',
    reminders: 'Email reminders',
    remindersOn: (email: string) => `Email reminders to ${email}`,
    remindersWhy: 'On by default. Reminders go by email only.',
    secondEmail: (company: string) => `Second email for ${company} (optional)`,
    secondEmailWhy: 'For example your agent',
    saveReminders: 'Save reminder settings',
    saved: 'Saved.',
    addCompany: 'Add another company',
    addEmployees: 'Add employees',
    dashboard: 'Go to dashboard',
    doer: { you: 'You', agent: 'Your agent' },
    complete: (item: string) => `Complete: ${item}`,
    items: {
      'legal-form': 'legal form',
      'licence-issue-date': 'licence issue date',
      'licence-expiry-date': 'licence expiry date',
      'expected-new-expiry': 'expected new licence expiry',
      'incorporation-date': 'date of incorporation',
      activities: 'activities',
      handler: 'who handles your zone paperwork',
      people: 'owners and managers',
      'passport-expiry': 'passport expiry',
      'visa-expiry': 'residence visa expiry',
      'emirates-id-expiry': 'Emirates ID expiry',
      'office-type': 'office type',
      'lease-end': 'contract or lease end date',
      'renews-with-licence': 'whether the lease renews with the licence',
      'establishment-card': 'establishment card expiry',
      'visa-quota': 'visa quota allowed',
      'visas-used': 'visas used now',
      'corporate-tax-registration': 'corporate tax registration',
      'first-tax-period-end': 'end date of the first tax period',
      'financial-year-end': 'financial year end',
      qfzp: 'Qualifying Free Zone Person status',
      'vat-registration': 'VAT registration',
      'vat-filing-period': 'VAT filing period',
      'vat-period-end': 'VAT tax period end date',
      'vat-threshold': 'VAT threshold answers',
    },
    taskTitles: {
      'corporate-tax-registration': 'Check corporate tax registration',
      'vat-threshold': 'Ask your accountant about VAT',
      'vat-registration': 'Check VAT registration',
    },
  },
  dated: {
    'licence-renewal': 'Licence renewal',
    'decision-point': 'Renew, cancel or change?',
    'lease-end': 'Office contract ends',
    'establishment-card': 'Establishment card expires',
    'passport-early-warning': 'Passport: early warning',
    'passport-alert': 'Passport: renew before the visa',
    'visa-expiry': 'Residence visa expires',
    'emirates-id-expiry': 'Emirates ID expires',
    'corporate-tax-registration': 'Register for corporate tax',
    'corporate-tax-return': 'Corporate tax return and payment',
    'vat-return': 'VAT return and payment',
  },
  todo: {
    'licence-renewal': 'Renew the licence with the zone.',
    'decision-point': 'Decide whether to renew, cancel or change the licence.',
    'lease-end': 'Renew the office or desk contract.',
    'establishment-card': 'Renew the establishment card.',
    'passport-early-warning': 'Plan the passport renewal.',
    'passport-alert': 'Renew the passport before the visa renewal.',
    'visa-expiry': 'Renew the residence visa.',
    'emirates-id-expiry': 'Renew the Emirates ID.',
    'corporate-tax-registration': 'Register on EmaraTax.',
    'corporate-tax-return': 'File the return and pay on EmaraTax.',
    'vat-return': 'File the return and pay on EmaraTax.',
  },
  panel: {
    title: 'Your dates so far',
    empty: 'Your dates appear here as you answer.',
    toggle: (count: number) => `Your dates so far (${String(count)})`,
    nextReminder: (date: string) => `Next reminder ${date}`,
    late: 'Late to register for corporate tax',
  },
  employees: {
    title: 'Employees on visas',
    why: 'Sponsor is this company. We watch their visa dates; no contracts, salary or WPS.',
    fullName: 'Full name',
    fullNameWhy: 'Their visa dates',
    passportWhy: (months: number) => `The ${String(months)}-month passport rule`,
    add: 'Add employee',
    none: 'No employees added yet.',
    done: 'Back to your year',
  },
} as const;
